name: sir_model_env
channels:
  - defaults
  - conda-forge
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.12.2=hca03da5_0
  - libffi=3.4.4=hca03da5_1
  - libzlib=1.3.1=h5f15de7_0
  - ncurses=6.5=hee39554_0
  - openssl=3.0.18=h9b4081a_0
  - pip=25.3=pyhc872135_0
  - python=3.11.9=hb885b13_0
  - readline=8.3=h0b18652_0
  - setuptools=80.9.0=py311hca03da5_0
  - sqlite=3.51.1=hab6afd1_0
  - tk=8.6.15=hcd8a7d5_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py311hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - contourpy==1.3.3
      - cycler==0.12.1
      - fonttools==4.61.1
      - kiwisolver==1.4.9
      - matplotlib==3.10.8
      - numpy==2.4.1
      - packaging==25.0
      - pillow==12.1.0
      - pyparsing==3.3.1
      - python-dateutil==2.9.0.post0
      - scipy==1.17.0
      - six==1.17.0
prefix: /opt/miniconda3/envs/sir_model_env
